# Generated by Django 3.0.8 on 2020-07-10 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('ticker', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('revenue', models.FloatField()),
                ('costOfRevenue', models.FloatField()),
                ('grossProfit', models.FloatField()),
                ('grossProfitRatio', models.FloatField()),
                ('researchAndDevelopmentExpenses', models.FloatField()),
                ('generalAndAdministrativeExpenses', models.FloatField()),
                ('sellingAndMarketingExpenses', models.FloatField()),
                ('otherExpenses', models.FloatField()),
                ('operatingExpenses', models.FloatField()),
                ('costAndExpenses', models.FloatField()),
                ('interestExpense', models.FloatField()),
                ('depreciationAndAmortization', models.FloatField()),
                ('ebitda', models.FloatField()),
                ('ebitdaratio', models.FloatField()),
                ('operatingIncome', models.FloatField()),
                ('operatingIncomeRatio', models.FloatField()),
                ('totalOtherIncomeExpensesNet', models.FloatField()),
                ('incomeBeforeTax', models.FloatField()),
                ('incomeBeforeTaxRatio', models.FloatField()),
                ('incomeTaxExpense', models.FloatField()),
                ('netIncome', models.FloatField()),
                ('netIncomeRatio', models.FloatField()),
                ('eps', models.FloatField()),
                ('epsdiluted', models.FloatField()),
                ('weightedAverageShsOut', models.FloatField()),
                ('weightedAverageShsOutDil', models.FloatField()),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyst.Security')),
            ],
        ),
    ]
