# Generated by Django 3.0.8 on 2020-07-10 20:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('analyst', '0002_auto_20200710_0856'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IncomeStatement',
        ),
        migrations.DeleteModel(
            name='Security',
        ),
    ]
